# Generated by Django 4.1 on 2023-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m'),
        ),
    ]
