# Generated by Django 4.1 on 2023-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='fotos',
        ),
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
    ]
